name: Build

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
        
    - name: Pre-install dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install gcc-multilib g++-multilib cmake nodejs libuv1-dev:i386
        
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Clone repository and build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .

    - name: Prepare artifacts folder
      run: |
        mkdir artifacts
        cp build/libnodemod.so artifacts/
        cp deps/node/lib/Release/linux/libnode.so.93 artifacts/

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-artifacts
        path: artifacts/